platform:
  - x64

cache:
  - '%LOCALAPPDATA%\electron\Cache'
  - node_modules -> package.json

install:
  - systeminfo | findstr /C:"OS"
  - set PATH=C:\Ruby23-x64\bin;%PATH%
  - ps: Install-Product node 10.13.0 x64
  - ps: .\build\install-yarn.ps1
  - yarn install --frozen-lockfile

build_script:
  - yarn generate
  - yarn lint-windows
  - yarn lint-deps
  - yarn test-node
  - node build\grunt.js
  - type package.json | findstr /v certificateSubjectName > temp.json
  - move temp.json package.json
  - yarn prepare-beta-build
  - node_modules\.bin\build --config.extraMetadata.environment=%SIGNAL_ENV% --publish=never --config.directories.output=release

test_script:
  - node build\grunt.js test
  - set NODE_ENV=production
  - node build\grunt.js test-release:win

environment:
  SIGNAL_ENV: production
